### ISSUE TITLE
Add support for space after the SQL comment and the string

### ISSUE THREAD

**Issue by Eitz** [derefs/vscode-inline-sql-highlight#1]
It would be ideal if your extension could support the following scenario:

![image](https://user-images.githubusercontent.com/6805910/108274127-c3cbf200-7174-11eb-9cc0-fe8f6a37f6ba.png)

I am asking this minor change because `prettier` auto-formats the line and adds that space and this is non-configurable, something that forces me to add a `// prettier-ignore` before every SQL statement.

**Comment by ionelaipatioaei** [comment]
Just pushed a new update that should allow a whitespace between the comment and the start of the string.

**Comment by Eitz** [comment]
Awesome, you rock, man!
